// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const datasource: {
  url: string | undefined;
  shadowDatabaseUrl?: string;
} = {
  url: process.env["DATABASE_URL"],
};

const direct = process.env["DIRECT_DATABASE_URL"]?.trim();
if (direct) {
  datasource.shadowDatabaseUrl = direct;
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "npx tsx prisma/seed.ts",
  },
  datasource,
})
